spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authentication
    username: authentication
    password: laisseMoiPasser2404@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
      format-sql: true
      database: sql
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect


 
     
      
    
